name: Dispatch Event to Playwright Automation Repo
description: An action to dispatch an event to a Playwright Automation Repo
inputs:
  repo:
    description: 'Target Repository - Playwright Automation Repo'
    required: true
  event-type:
    description: 'Event type for the repository dispatch'
    required: true
  client-payload:
    description: 'JSON payload to send with the dispatch'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
