name: Dispatch Event
description: An action to dispatch an event to another repository
inputs:
  repo:
    description: 'Target repository (e.g., organization/repoB)'
    required: true
  event-type:
    description: 'Event type for the repository dispatch'
    required: true
  client-payload:
    description: 'JSON payload to send with the dispatch'
    required: true
  repo-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
