name: Dispatch Event

description: An action to dispatch an event to another repository

inputs:
  repo:
    description: 'Plawyright Automation Repository'
    required: true
  event-type:
    description: 'Run Tests'
    required: true
  client-payload:
    description: 'JSON payload to send with the event'
    required: true

runs:
  using: 'node16'
  pre:
    run: npm install
  main: 'index.js'
