name: Test Local Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Local Action
        uses: ./ 
        with:
          repo: 'afonte15/playwright-demo'
          event-type: 'run-tests'
          client-payload: '{"env": "qa", "grep": "@e2e"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
