name: Run Tagged Playwright Tests

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to filter tests'
        required: true
        type: string
      playwright_repo:
        description: 'Playwright Automation Repository'
        required: true
        type: string
      playwright_repo_ref:
        description: 'Branch or commit to use in the Playwright repository'
        required: false
        type: string
        default: 'main'
      environment:
        description: 'Environment to run the tests against'
        required: true
        type: string
      run_command:
        description: 'Command to run the Playwright tests'
        required: true
        type: string
    secrets:
      REPO_GITHUB_TOKEN:
        required: true
      QA_BASE_URL:
        required: false
      QA_ENVIRONMENT:
        required: false
      STAGING_BASE_URL:
        required: false
      STAGING_ENVIRONMENT:
        required: false

jobs:
  run-tagged-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment Before Dispatch
        run: |
          if [ "${{ inputs.environment }}" == "qa" ]; then
            echo "Dispatching tests against the QA environment"
          elif [ "${{ inputs.environment }}" == "staging" ]; then
            echo "Dispatching tests against the Staging environment"
          else
            echo "Dispatching tests against an unknown environment"
          fi

      - name: Checkout Playwright Automation Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.playwright_repo }}
          ref: ${{ inputs.playwright_repo_ref }}
          token: ${{ secrets.REPO_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.environment }}" == "qa" ]; then
            echo "BASE_URL=${{ secrets.QA_BASE_URL }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=${{ secrets.QA_ENVIRONMENT }}" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "staging" ]; then
            echo "BASE_URL=${{ secrets.STAGING_BASE_URL }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=${{ secrets.STAGING_ENVIRONMENT }}" >> $GITHUB_ENV
          fi

      - name: Log Environment Variables
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "Base URL: $BASE_URL"

      - name: Run Playwright Tests with Tag
        run: TEST_ENV=${{ inputs.environment }} ${{ inputs.run_command }} --grep @${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}